name: playwright tests

on:
  push:
   branches:
    - main
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v22.18.0

      - name: Install dependencies
        run: npm install

      - name: Run all tests
        run: npx playwright test --reporter=list

      - name: Generate HTML report
        run: npx playwright show-report

      - name: Generate Allure report
        run:  npx allure generate allure-results --clean && npx allure open
